#!/usr/bin/perl -w
#HandBrake
use strict;

my @questions = (
		'Rip DVD' , 
		'Rip File' , 
		'Exit Program'
		);
my @solutions = (
		system("perl /opt/MediaServerTools/Programs/HandBrake/scripts/RIP-DVD") ,
		system("perl /opt/MediaServerTools/Programs/HandBrake/scripts/RIP-FILE")  ,
		die
	);

for (0..$#questions) {
			print "How many $questions[$_] ";
			print "programmers does it take to change a lightbulb?\n\n";
			sleep 2;
			print $punchlines[$_],  "\n\n";
			sleep 1;
	}

#print "Please enter a number between 1 and 4: ";
#my $selection = <STDIN>;
#$selection -=1