#!usr/bin/perl -w
#MountDVD
use strict;

my $mountStatus;
my $mountFrom = "/dev/cdrom";
my $mountTo = "/opt/MediaServerTools/Programs/HandBrake/cdrom";

system("mount $mountFrom $mountTo");
print "Disk Mounted Succesfully\n";