#!usr/bin/perl -w
#RIP-DVD
use strict;

sub myHeader {
		print "  :::::::: Handbrake DVD Ripping Program :::::::::  ";
}
sub myunMountPeskys {
		#Unmount any Drives that could cause a mishap
		system('perl /opt/MediaServerTools/Programs/HandBrake/scripts/unMountDVD');
		system ('perl umount /MediaServerTools');	
}
myunMountPeskys();


sleep 1;
system("clear");

myHeader();
print "\n\n\n\n";

#Variables
my $file_to_Rip = "/opt/MediaServerTools/Programs/HandBrake/cdrom/VIDEO_TS";
my $rip_file_to = "/opt/MediaServerTools/Programs/HandBrake/RAW/RIPPED/";
my $movie_directory = "/home/plex/Movies/";
my $rip_file_format = ".mp4";
my $script_directory = "/opt/MediaServerTools/Programs/HandBrake/scripts/";
my $get_rip_file_name;


#Mount DVD
print "Mounting DVD\nPlease Wait...\n\n";
sleep 2;
system('perl ' . $script_directory . 'MountDVD') == 0 or die "Failed to Mount DVD, Check that the device is ready.\n";
print "DVD Mounted \n\n\n\n";


print "What is the name of the Movie?  :  ";
$get_rip_file_name = <STDIN>;
chomp $get_rip_file_name;
$get_rip_file_name=~ s/\s//g;
sleep 1;

print "Ripping Movies...";
sleep 1;
my $ripped_file_output = $rip_file_to . $get_rip_file_name . $rip_file_format;
system('HandBrakeCLI -i ' . $file_to_Rip . ' -o ' . $ripped_file_output . ' -e x264 -q 20 -B 160 -t 1 ') == 0 or die "Failed to RIP DVD\n\n";
print "\n\n\n";
print "Disk Ripped Succesfully\n\n";
sleep 2;
system("clear");


#Move Ripped File to the Movies Directory
myHeader();
print "Moving Ripped file to Local Movies Directory";
sleep 3;
my $move_dir_withFile = $movie_directory . $get_rip_file_name . $rip_file_format;
system('mv ' . $ripped_file_output . ' ' . $move_dir_withFile) == 0 or die "Failed to Move Ripped File to Movies Directory\n\n";
print "\n";
system("clear");

myHeader();
print "\n\nFile Moved Succesfully\n\n\n";
sleep 2;

#Unmount DVD
sleep 1;
system('perl ' . $script_directory . 'unMountDVD') == 0 or die "Failed to unMount DVD\n\n";
print "DVD Released\n\n\n\n\n\n";



