#!usr/bin/perl
#MediaServerConfig
use warnings;
use strict;
use File::Copy;
use File::Path qw(make_path remove_tree); 

#Declare Variables for the System Files
my $ssh_FilesF;
my $ssh_FilesT;
my $sysconfig_Files1F;
my $sysconfig_Files1T;
my $sysconfig_Files2F;
my $sysconfig_Files2T;
my $sysconfig_Files3F;
my $sysconfig_Files3T;
my $yumrepo_Files1F;
my $yumrepo_Files1T;
my $yumrepo_Files2F;
my $yumrepo_Files2T;
my $programupdate_FilesF;
my $programupdate_FilesT;
my $Plexscripts_Files1F;
my $Plexscripts_Files1T;
my $Plexscripts_Files2F;
my $Plexscripts_Files2T;
my $Plexscripts_Files3F;
my $Plexscripts_Files3T;
my $Plexscripts_Files4F;
my $Plexscripts_Files4T;
my $Plexscripts_Files5F;
my $Plexscripts_Files5T;
my $Plexscripts_Files6F;
my $Plexscripts_Files6T;
my $HandBrakescripts_Files1F;
my $HandBrakescripts_Files1T;
my $HandBrakescripts_Files2F;
my $HandBrakescripts_Files2T;
my $HandBrakescripts_Files3F;
my $HandBrakescripts_Files3T;
my $HandBrakescripts_Files4F;
my $HandBrakescripts_Files4T;
my $HandBrakescripts_Files5F;
my $HandBrakescripts_Files5T;
my $HandBrakescripts_Files6F;
my $HandBrakescripts_Files6T;
my $HandBrakescripts_Files7F;
my $HandBrakescripts_Files7T;
my $HandBrakescripts_Files8F;
my $HandBrakescripts_Files8T;
my $ServerTools_Files1F;
my $ServerTools_Files1T;
my $ServerTools_Files2F;
my $ServerTools_Files2T;

#Install Needed Core Programs
system("clear");
sleep 1;
print "\n\n\n\n";
print "Preparing to install Core Programs from the internet\n\n";
sleep 2;
system("yum install nano man wget zip unzip -y");
print "\n\n\n";
print "The Following programs have been installed \n----> nano \n----> man \n----> wget \n----> zip \n----> unzip\n\n";

#Copy the ssh Files for OpenSSH Access and Restart Service
$ssh_FilesF = "/MediaServerTools/MediaServer/configs/etc/ssh/sshd_config";
$ssh_FilesT = "/etc/ssh/";
copy($ssh_FilesF, $ssh_FilesT) or die "SSH File could not be copied $!";
print "Restarting the OpenSSH Service. \n";
sleep 1;
system("service sshd restart");
sleep 1;
print "\n\n\n\n";
print "1. SSH File copied Successfully. Service Restarted \n";


#Make the directories needed for configuration
make_path(
'/opt/MediaServerTools/Programs/HandBrake/Updates' ,
'/opt/MediaServerTools/Programs/HandBrake/RAW/RIPPED' ,
'/opt/MediaServerTools/Programs/HandBrake/scripts' ,
'/opt/MediaServerTools/Programs/Plex/Updates' , 
'/opt/plex' , 
'/home/plex/Movies'
);
print "2. All opt Directory Creation Scripts have run Successfully\n";
sleep 1;

#Copy the Update Files into the Newly created Programs Directories
####I need to check for file existence and overwriting capabilities
$programupdate_FilesF = "/MediaServerTools/MediaServer/Programs/Plex/Updates/plexmediaserver-0.9.6.9.240-8fd9c6a.x86_64.rpm";
$programupdate_FilesT = "/opt/MediaServerTools/Programs/Plex/Updates/plexmediaserver-0.9.6.9.240-8fd9c6a.x86_64.rpm";
copy($programupdate_FilesF, $programupdate_FilesT) or die "Opt/MediaServerTools Files could not be created $!";
print "3. Update files copied Successfully \n";
sleep 1;

#Copy the Update & Program Files into the Newly created Programs Directories
####I need to check for file existence and overwriting capabilities
$HandBrakescripts_Files1F;
$HandBrakescripts_Files1T;
$HandBrakescripts_Files2F;
$HandBrakescripts_Files2T;
$HandBrakescripts_Files3F;
$HandBrakescripts_Files3T;
print "4. Program Script files copied Successfully \n";
sleep 1;

#Copy the Media Server Tools Files into the Root Directory
####I need to check for file existence and overwriting capabilities
$ServerTools_Files1F = "/MediaServerTools/MediaServer/help/MountServerFiles";
$ServerTools_Files1T = "/MountServerFiles";
$ServerTools_Files2F = "/MediaServerTools/MediaServer/help/unMountServerFiles";
$ServerTools_Files2T = "/unMountServerFiles";
copy($ServerTools_Files1F, $ServerTools_Files1T) or die "MediaServerTools Helper Files could not be created $!";
#copy($ServerTools_Files2F, $ServerTools_Files2T) or die "MediaServerTools Helper Files could not be created $!";
my $mode = 0755;   
chmod $mode, $ServerTools_Files1T;	
#chmod $mode, $ServerTools_Files2T;
print "5. Helper files copied Successfully \n";
sleep 1;

#Copy the ssh Files
$yumrepo_Files1F = "/MediaServerTools/MediaServer/configs/etc/yum.repos.d/plex.repo";
$yumrepo_Files2F = "/MediaServerTools/MediaServer/configs/etc/yum.repos.d/linuxtech.repo";
$yumrepo_Files1T = "/etc/yum.repos.d/plex.repo";
$yumrepo_Files2T = "/etc/yum.repos.d/linuxtech.repo";
copy($yumrepo_Files1F, $yumrepo_Files1T) or die "YumRepo File -plex.repo- could not be copied $!";
copy($yumrepo_Files2F, $yumrepo_Files2T) or die "YumRepo File -linuxtech.repo- could not be copied $!";
print "6. All YumRepo Files copied Successfully \n\n";
sleep 1;

#Install the Media server and Ripping Programs
print "\n\n\n\n";
print "Preparing to install Media Server and HandBrake\n";
sleep 2;
print "---------------------------------------------------\n";
system("yum install plexmediaserver.x86_64 handbrake-cli.x86_64 -y");
print "---------------------------------------------------\n";
print "PlexMediaServer & HandBrake have been Installed.\n";
sleep 1;

#Install the Media server and Ripping Programs local Updates
print "\n\n\n\n";
print "Installing the Media server and Ripping Programs local Updates\n";
sleep 2;
print "---------------------------------------------------\n";
system("yum localupdate /opt/MediaServerTools/Programs/Plex/Updates/plexmediaserver-0.9.6.9.240-8fd9c6a.x86_64.rpm -y");
print "---------------------------------------------------\n";
print "PlexMediaServer has been locally Updated.\n\n";
sleep 1;

#Declare Plex Directories and Change the owner 
my $uid = getpwnam('plex');
my $gid = getgrnam('plex');
my @files_to_chown = qw(/home/plex/ 
										/home/plex/Movies 
										/opt/plex
										);
my $chownFiles;
print "---------------------------------------------------\n";
for $chownFiles (@files_to_chown) {
	chown $uid, $gid, $chownFiles;
	print "Successfully Chowned $chownFiles\n";
}
print "---------------------------------------------------\n";
print "\nThe CHOWN operation was successful\n";

#Copy the sysconfig Files
$sysconfig_Files1F = "/MediaServerTools/MediaServer/configs/etc/sysconfig/iptables";
$sysconfig_Files2F = "/MediaServerTools/MediaServer/configs/etc/sysconfig/network";
$sysconfig_Files3F = "/MediaServerTools/MediaServer/configs/etc/sysconfig/PlexMediaServer";
$sysconfig_Files1T = "/etc/sysconfig/iptables";
$sysconfig_Files2T = "/etc/sysconfig/network";
$sysconfig_Files3T = "/etc/sysconfig/PlexMediaServer";
copy($sysconfig_Files1F, $sysconfig_Files1T) or die "Sysconfig File -iptables- could not be copied $!";
copy($sysconfig_Files2F, $sysconfig_Files2T) or die "Sysconfig File -network-could not be copied $!";
copy($sysconfig_Files3F, $sysconfig_Files3T) or die "Sysconfig File -PlexMediaServer- could not be copied $!";
print "\nAll Sysconfig Files copied Successfully \n\n\n\n\n\n\n\n";



#system("reboot");
